version: "3.8"

services:
  minecraft:
    container_name: forge_1.12.2_server
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft/server/mods:/server/mods # MODディレクトリだけホストからマウント
    build:
      context: .
      dockerfile: ./docker/MCServer/Dockerfile
    environment:
      - FORGE_VERSION=14.23.5.2860
      - MC_VERSION=1.12.2
