version: "3.8"

services:
  minecraft:
    container_name: forge_1.12.2_server
    image: openjdk:8-jre-slim
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft/server:/server
    working_dir: /server
    command: ["java", "-Xmx2G", "-Xms1G", "-jar", "forge-1.12.2-14.23.5.2860.jar", "nogui"]
